# Generated by Django 4.0.6 on 2022-12-10 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=30)),
                ('phone', models.CharField(default='', max_length=10)),
                ('address', models.CharField(max_length=60, unique=True)),
                ('vacancies', models.IntegerField(default=0)),
                ('additional_info', models.CharField(blank=True, max_length=300)),
            ],
        ),
    ]
