# Generated by Django 4.0.6 on 2022-12-10 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_shelter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=60)),
                ('time_range', models.CharField(max_length=60)),
                ('condition', models.CharField(max_length=300)),
            ],
        ),
    ]
