# Generated by Django 4.0.6 on 2022-12-11 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_donation_user_shelter_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelter',
            name='city',
            field=models.CharField(default='', max_length=60),
        ),
    ]
