# Generated by Django 4.0.6 on 2022-12-11 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_shelter_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='city',
            field=models.CharField(default='', max_length=60),
        ),
    ]
