# Generated by Django 4.0.6 on 2022-12-11 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_donation_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saved_shelters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Shelter', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='shelters', to='project.shelter')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='users', to='project.user')),
            ],
        ),
    ]
