# Generated by Django 4.0.6 on 2022-12-11 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_saved_shelters'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Saved_shelters',
            new_name='Save',
        ),
    ]
